# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dc3706831f2a6376468ea68cb02b0c5af00b6ed770e1891cb6953922a2e2c600971700318ca39a699a0d7e402d43bb1e7763d7504cab4eead158b20100d751a

test:
  secret_key_base: fe67a7316269369ff4fefa220d8d288673a006c78cef1722cf3b91612719b91c367166b1a190831d3a4879f536152caf6df1a9f1c88edbb0b7d404bbb6a2ea1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
